#! /bin/bash

echo ${BASH_SOURCE[0]}

BASE_PATH=`dirname ${BASH_SOURCE[0]}`
ACTUAL_BASE_PATH=`cd $BASE_PATH && pwd`

INVICTUS_ROOT=`dirname $ACTUAL_BASE_PATH`
export INVICTUS_ROOT
echo "Using: "$INVICTUS_ROOT "as INVICTUS_ROOT"

QTDIR=$INVICTUS_ROOT/Qt
export QTDIR
#echo "Using: "$QTDIR "as QTDIR"

#DBROOTDIR=$INVICTUS_ROOT/BerkeleyDB
#export DBROOTDIR
#echo "Using: "$DBROOTDIR "as DBROOTDIR"

#export OPENSSL_ROOT=$INVICTUS_ROOT/OpenSSL
#export OPENSSL_ROOT_DIR=$OPENSSL_ROOT
#export OPENSSL_INCLUDE_DIR=$OPENSSL_ROOT/include
#echo "Using: "$OPENSSL_ROOT_DIR " as OPENSSL_ROOT"
#export ICUROOT=$INVICTUS_ROOT/icu

#export BOOST_ROOT=$INVICTUS_ROOT/boost


export CMAKE_PREFIX_PATH=$INVICTUS_ROOT/OpenSSL:$INVICTUS_ROOT/icu:$INVICTUS_ROOT/BerkeleyDB:$QTDIR/5.2.1/clang_64
export DYLD_FRAMEWORK_PATH=$QTDIR/5.2.1/clang_64/lib:$DYLD_FRAMEWORK_PATH